### ISSUE TITLE
Application closing bug 

### ISSUE THREAD

**Issue by pponec** [pponec/jworksheet#2]
The jWorkSheet application running with the systray icon can' be closed correctly.

Environment:  

* Java 11, 
* Linux Xubuntu 20.04 LTS

**Comment by d-led** [comment]
commenting out that hook fixes the problem: https://github.com/pponec/jworksheet/blob/master/src/main/java/net/ponec/jworksheet/gui/JWorkSheet.java#L267-L273

there's already [another hook](https://github.com/pponec/jworksheet/blob/master/src/main/java/net/ponec/jworksheet/gui/JWorkSheet.java#L257-L262), so there's probably a race condition finalizing the app

**Comment by pponec** [comment]
> there's already [another hook](https://github.com/pponec/jworksheet/blob/master/src/main/java/net/ponec/jworksheet/gui/JWorkSheet.java#L257-L262), so there's probably a race condition finalizing the app

Thank you for the notification, the bug is fixed.

**Comment by pponec** [comment]
At first glance, it looks like the application is closed properly, but unfortunately the system process will continue.

**Comment by d-led** [comment]
I've rather tried the other simple hook. This worked on OSX:

```diff
--- a/src/main/java/net/ponec/jworksheet/gui/JWorkSheet.java
+++ b/src/main/java/net/ponec/jworksheet/gui/JWorkSheet.java
@@ -253,15 +253,12 @@ public final class JWorkSheet extends TopFrame {
                 }
             });
 
-            // Set a terminate hook (https://www.baeldung.com/jvm-shutdown-hooks):
-            running = true;
-            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
-                if (running) {
-                    running = false;
+            Runtime.getRuntime().addShutdownHook(new Thread(){^M
+                @Override^M
+                public void run() {^M
                     closeAppl(null);
                 }
-                System.exit(0);
-            }));
```

**Comment by pponec** [comment]
Thank you for information, the bug is fixed today.

**Comment by d-led** [comment]
thanks for the pragmatic tool likewise!
